In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
train_df = pd.read_csv('All_numbers.csv')
train_df.head()

,Unnamed: 0,ID,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Side,City,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,0,A-1,3,40.108910,-83.092860,40.112060,-83.031870,3.230,2,481,...,False,False,False,False,False,False,3,3,3,3
1,1,A-2,2,39.865420,-84.062800,39.865010,-84.048730,0.747,2,108,...,False,False,False,False,False,False,3,3,3,3
2,2,A-3,2,39.102660,-84.524680,39.102090,-84.523960,0.055,2,160,...,False,False,False,False,False,False,3,3,3,2
3,3,A-4,2,41.062130,-81.537840,41.062170,-81.535470,0.123,2,561,...,False,False,False,False,False,False,3,3,2,2
4,4,A-5,3,39.172393,-84.492792,39.170476,-84.501798,0.500,2,160,...,False,False,False,False,False,False,2,2,2,2

In [ ]:
train_df.drop('Unnamed: 0', axis=1, inplace=True)
train_df.drop('ID', axis=1, inplace=True)
train_df.drop('Country', axis=1, inplace=True)

In [ ]:
train_df.drop('Wind_Chill(F)', axis=1, inplace=True)
train_df.drop('Humidity(%)', axis=1, inplace=True)
train_df.drop('Wind_Speed(mph)', axis=1, inplace=True)
train_df.drop('Precipitation(in)', axis=1, inplace=True)

KeyError: ignored

In [ ]:
train_df.head()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Side,City,County,State,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,3,40.108910,-83.092860,40.112060,-83.031870,3.230,2,481,119,25,...,False,False,False,False,False,False,3,3,3,3
1,2,39.865420,-84.062800,39.865010,-84.048730,0.747,2,108,15,25,...,False,False,False,False,False,False,3,3,3,3
2,2,39.102660,-84.524680,39.102090,-84.523960,0.055,2,160,43,25,...,False,False,False,False,False,False,3,3,3,2
3,2,41.062130,-81.537840,41.062170,-81.535470,0.123,2,561,171,25,...,False,False,False,False,False,False,3,3,2,2
4,3,39.172393,-84.492792,39.170476,-84.501798,0.500,2,160,43,25,...,False,False,False,False,False,False,2,2,2,2

In [ ]:
y = train_df["Severity"]
y = y-1
np.unique(y)

array([0, 1, 2, 3], dtype=int64)

In [ ]:
train_df.drop('Severity', axis=1, inplace=True)
train_df.head()

,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Side,City,County,State,Zipcode,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,40.108910,-83.092860,40.112060,-83.031870,3.230,2,481,119,25,43017,...,False,False,False,False,False,False,3,3,3,3
1,39.865420,-84.062800,39.865010,-84.048730,0.747,2,108,15,25,45424,...,False,False,False,False,False,False,3,3,3,3
2,39.102660,-84.524680,39.102090,-84.523960,0.055,2,160,43,25,45203,...,False,False,False,False,False,False,3,3,3,2
3,41.062130,-81.537840,41.062170,-81.535470,0.123,2,561,171,25,44311,...,False,False,False,False,False,False,3,3,2,2
4,39.172393,-84.492792,39.170476,-84.501798,0.500,2,160,43,25,45217,...,False,False,False,False,False,False,2,2,2,2

In [ ]:
train_df.columns.values.tolist()

['Start_Lat',
 'Start_Lng',
 'End_Lat',
 'End_Lng',
 'Distance(mi)',
 'Side',
 'City',
 'County',
 'State',
 'Zipcode',
 'Timezone',
 'Temperature(F)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Direction',
 'Weather_Condition',
 'Amenity',
 'Bump',
 'Crossing',
 'Give_Way',
 'Junction',
 'No_Exit',
 'Railway',
 'Roundabout',
 'Station',
 'Stop',
 'Traffic_Calming',
 'Traffic_Signal',
 'Turning_Loop',
 'Sunrise_Sunset',
 'Civil_Twilight',
 'Nautical_Twilight',
 'Astronomical_Twilight']

In [ ]:
import copy

frames = copy.deepcopy(train_df)

In [ ]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import MinMaxScaler

# for column in train_df:
#   print(column)
#   scaler = MinMaxScaler()
#   data = np.array(train_df[column])
#   data = data.reshape(data.shape[0], 1)
#   scaler.fit(data)
#   #print(scaler.data_max_)
#   data = scaler.transform(data)
#   print(np.max(data))
#   train_df[column] = data

In [ ]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.ensemble import AdaBoostClassifier

X_train, X_test, y_train, y_test = train_test_split(train_df, y, test_size=0.2, random_state=1)

In [ ]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1 score:",metrics.f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.8768391882179489
F1 score: 0.878106332933228

In [ ]:
depths = list(range(5,55,5))
depths

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [ ]:
max_depth = 5
accuracies = []
f1_scores = []
while max_depth<=50:
  clf = DecisionTreeClassifier(max_depth=max_depth)

  # Train Decision Tree Classifer
  clf = clf.fit(X_train,y_train)

  #Predict the response for test dataset
  y_pred = clf.predict(X_test)
  accuracy = metrics.accuracy_score(y_test, y_pred)
  accuracies.append(accuracy)
  f1_score = metrics.f1_score(y_test, y_pred, average='weighted')
  f1_scores.append(f1_score)
  print("Depth is "+str(max_depth)+" Accuracy is "+str(accuracy)+" F1 score is"+str(f1_score))
  max_depth += 5
print("Accuracies are "+str(accuracies))
print("F1 scores are "+str(f1_scores))

Depth is 5 Accuracy is 0.8956137129240918 F1 score is0.8555039290154492
Depth is 10 Accuracy is 0.9019890382361365 F1 score is0.8767870455975124
Depth is 15 Accuracy is 0.9040116400647373 F1 score is0.8846035638798294
Depth is 20 Accuracy is 0.9015391806617475 F1 score is0.8873548621570938
Depth is 25 Accuracy is 0.8956576443278408 F1 score is0.8870802890162881
Depth is 30 Accuracy is 0.8881488887990736 F1 score is0.8839254660097129

KeyboardInterrupt: ignored

In [ ]:
plt.plot(depths, f1_scores)
plt.title("f1_scores")
plt.show()

In [ ]:
plt.plot(depths,accuracies)
plt.title("Accuracies ")
plt.show()

In [ ]:
#Ensemble methods
abc = AdaBoostClassifier(n_estimators=50,
                         learning_rate=1)
# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1 score:",metrics.f1_score(y_test, y_pred, average='weighted'))